# Load modules

In [1]:
%load_ext autoreload
%autoreload 2

# Standard library imports
import pickle

# Third-party library imports
import numpy as np

# DFTTK imports
from dfttk.thermal_electronic.functions import ThermalElectronic

# test_read_total_electron_dos()

In [3]:
# Set the path to the VASP configuration directory and initialize the ThermalElectronic object
config_Al_path = "../vasp_data/Al/config_Al"
thermal_electronic = ThermalElectronic()

In [4]:
# For all volumes:

# Read electron DOS from elec_* folders
thermal_electronic.read_total_electron_dos(path=config_Al_path)

# Print expected results for verification
print(thermal_electronic.path)
print(thermal_electronic.number_of_atoms)
print(thermal_electronic.volumes)
print(thermal_electronic.energies_list)
print(thermal_electronic.dos_list)

# Save energies_list and dos_list to pickle files (these arrays are large)
with open("expected_energies_list.pkl", "wb") as f:
    pickle.dump(thermal_electronic.energies_list, f)
with open("expected_dos_list.pkl", "wb") as f:
    pickle.dump(thermal_electronic.dos_list, f)


/jet/home/nhew/.local/lib/python3.12/site-packages/pymatgen/io/vasp/outputs.py:1285: UserWarning: No POTCAR file with matching TITEL fields was found in

  if potcar := self.get_potcars(path):
/jet/home/nhew/.local/lib/python3.12/site-packages/pymatgen/io/vasp/outputs.py:1296: UserWarning: No POTCAR file with matching TITEL fields was found in

  potcar = self.get_potcars(path)


../vasp_data/Al/config_Al
4
[60. 62. 64. 66. 68. 70. 72. 74.]
[array([-16.14507986, -16.13547986, -16.12587986, ...,  79.54112014,
        79.55062014,  79.56022014]), array([-15.81409607, -15.80469607, -15.79529607, ...,  77.81950393,
        77.82890393,  77.83820393]), array([-15.49769456, -15.48859456, -15.47939456, ...,  76.18480544,
        76.19400544,  76.20310544]), array([-15.19526904, -15.18626904, -15.17726904, ...,  74.63303096,
        74.64203096,  74.65103096]), array([-14.90544578, -14.89664578, -14.88784578, ...,  73.15975422,
        73.16855422,  73.17735422]), array([-14.62820387, -14.61950387, -14.61090387, ...,  71.75729613,
        71.76589613,  71.77449613]), array([-14.36286472, -14.35436472, -14.34586472, ...,  70.42043528,
        70.42893528,  70.43733528]), array([-14.10871788, -14.10041788, -14.09211788, ...,  69.14698212,
        69.15538212,  69.16368212])]
[array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., .

In [5]:
# For selected volumes:

selected_volumes = np.array([60., 66.])

# Read electron DOS from elec_* folders
thermal_electronic.read_total_electron_dos(path=config_Al_path, selected_volumes=selected_volumes)

# Print expected results for verification
print(thermal_electronic.path)
print(thermal_electronic.number_of_atoms)
print(thermal_electronic.volumes)
print(thermal_electronic.energies_list)
print(thermal_electronic.dos_list)


../vasp_data/Al/config_Al
4
[60. 66.]
[array([-16.14507986, -16.13547986, -16.12587986, ...,  79.54112014,
        79.55062014,  79.56022014]), array([-15.19526904, -15.18626904, -15.17726904, ...,  74.63303096,
        74.64203096,  74.65103096])]
[array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.])]


In [6]:
# For invalid selected volumes (should raise an error):

selected_volumes = np.array([59., 66.])

# Read electron DOS from elec_* folders
thermal_electronic.read_total_electron_dos(path=config_Al_path, selected_volumes=selected_volumes)

# Print expected results for verification
print(thermal_electronic.path)
print(thermal_electronic.number_of_atoms)
print(thermal_electronic.volumes)
print(thermal_electronic.energies_list)
print(thermal_electronic.dos_list)

ValueError: The following selected volumes were not found: [59.0]

In [ ]:
# TODO: For inconsistent number of atoms:

In [ ]:
# TODO: Test inconsistent number of electrons:

# test_set_total_electron_dos()

In [ ]:
# Set the path to the VASP configuration directory and initialize the ThermalElectronic object
thermal_electronic = ThermalElectronic()

In [ ]:
number_of_atoms = 4 
volumes = np.array([60., 62., 64., 66., 68., 70., 72., 74.])

# Load energies_list and dos_list from pickle files
with open("expected_energies_list.pkl", "rb") as f:
    energies_list = pickle.load(f)
with open("expected_dos_list.pkl", "rb") as f:
    dos_list = pickle.load(f)

# Set the electron DOS yourself
thermal_electronic.set_total_electron_dos(
    number_of_atoms=number_of_atoms,
    volumes=volumes,
    energies_list=energies_list,
    dos_list=dos_list
)

# Print expected results for verification
print(thermal_electronic.path)
print(thermal_electronic.number_of_atoms)
print(thermal_electronic.volumes)
print(thermal_electronic.energies_list)
print(thermal_electronic.dos_list)

None
4
[60. 62. 64. 66. 68. 70. 72. 74.]
[array([-16.14507986, -16.13547986, -16.12587986, ...,  79.54112014,
        79.55062014,  79.56022014]), array([-15.81409607, -15.80469607, -15.79529607, ...,  77.81950393,
        77.82890393,  77.83820393]), array([-15.49769456, -15.48859456, -15.47939456, ...,  76.18480544,
        76.19400544,  76.20310544]), array([-15.19526904, -15.18626904, -15.17726904, ...,  74.63303096,
        74.64203096,  74.65103096]), array([-14.90544578, -14.89664578, -14.88784578, ...,  73.15975422,
        73.16855422,  73.17735422]), array([-14.62820387, -14.61950387, -14.61090387, ...,  71.75729613,
        71.76589613,  71.77449613]), array([-14.36286472, -14.35436472, -14.34586472, ...,  70.42043528,
        70.42893528,  70.43733528]), array([-14.10871788, -14.10041788, -14.09211788, ...,  69.14698212,
        69.15538212,  69.16368212])]
[array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), arr

In [ ]:
# For different lengths of volumes, energies_list, and dos_list (should raise an error):
number_of_atoms = 4 
volumes = np.array([60., 62., 64., 66., 68., 70., 72.])

# Load energies_list and dos_list from pickle files
with open("expected_energies_list.pkl", "rb") as f:
    energies_list = pickle.load(f)
with open("expected_dos_list.pkl", "rb") as f:
    dos_list = pickle.load(f)

# Set the electron DOS yourself
thermal_electronic.set_total_electron_dos(
    number_of_atoms=number_of_atoms,
    volumes=volumes,
    energies_list=energies_list,
    dos_list=dos_list
)

ValueError: Lengths of volumes, energies_list, and dos_list must be the same.

# test_process()

In [15]:
# Set the path to the VASP configuration directory and initialize the ThermalElectronic object
config_Al_path = "../vasp_data/Al/config_Al"
thermal_electronic = ThermalElectronic()

In [16]:
# Process wihout setting the DOS (should raise an error)
thermal_electronic.process(temperatures=np.array([300, 600, 900]))

ValueError: DOS data not found. Please read or set the total electron DOS first using read_total_electron_dos() or set_total_electron_dos().

In [17]:
# Read electron DOS from elec_* folders for all volumes
thermal_electronic.read_total_electron_dos(path=config_Al_path)

/jet/home/nhew/.local/lib/python3.12/site-packages/pymatgen/io/vasp/outputs.py:1285: UserWarning: No POTCAR file with matching TITEL fields was found in

  if potcar := self.get_potcars(path):
/jet/home/nhew/.local/lib/python3.12/site-packages/pymatgen/io/vasp/outputs.py:1296: UserWarning: No POTCAR file with matching TITEL fields was found in

  potcar = self.get_potcars(path)


In [14]:
temperatures = np.array([0, 300, 600, 900])

# Process the thermal electronic properties
thermal_electronic.process(temperatures=temperatures)

print(thermal_electronic.temperatures)
print()
print(thermal_electronic.helmholtz_energies)
print()
print(thermal_electronic.internal_energies)
print()
print(thermal_electronic.entropies)
print()
print(thermal_electronic.heat_capacities)

[  0 300 600 900]

[[-6.73648444e-08 -8.49219646e-08 -6.37930199e-07 -2.47784314e-07
  -4.17356560e-07 -1.94288120e-07 -8.37631909e-07 -7.06400130e-07]
 [-1.86812194e-03 -1.94212095e-03 -2.01034372e-03 -2.04885416e-03
  -2.07876817e-03 -2.11227531e-03 -2.14827701e-03 -2.18280849e-03]
 [-7.43625295e-03 -7.70784476e-03 -7.95363672e-03 -8.13724063e-03
  -8.28299483e-03 -8.41321496e-03 -8.54203925e-03 -8.65734626e-03]
 [-1.65370414e-02 -1.71079727e-02 -1.76229463e-02 -1.80374507e-02
  -1.83793761e-02 -1.86755333e-02 -1.89589683e-02 -1.92030741e-02]]

[[-6.73648444e-08 -8.49219646e-08 -6.37930199e-07 -2.47784314e-07
  -4.17356560e-07 -1.94288120e-07 -8.37631909e-07 -7.06400130e-07]
 [ 1.87288067e-03  1.93643996e-03  1.99433637e-03  2.05074681e-03
   2.09172870e-03  2.12162543e-03  2.15042343e-03  2.17618076e-03]
 [ 7.29105411e-03  7.52653664e-03  7.73358755e-03  7.93143942e-03
   8.10121120e-03  8.23313062e-03  8.34962180e-03  8.44030084e-03]
 [ 1.59001038e-02  1.63515358e-02  1.67643207e-0

# test_fit()

In [4]:
# Set the path to the VASP configuration directory and initialize the ThermalElectronic object
config_Al_path = "../vasp_data/Al/config_Al"
thermal_electronic = ThermalElectronic()

In [5]:
# Read electron DOS from elec_* folders for all volumes
thermal_electronic.read_total_electron_dos(path=config_Al_path)

In [29]:
volumes_fit = np.linspace(0.98*60, 1.02*74, 10)
order = 1

# Try to call fit without process (should raise an error)
thermal_electronic.fit(volumes_fit=volumes_fit, order=order)

ValueError: Thermodynamic properties not yet calculated. Please call process() first

In [6]:
temperatures = np.array([0, 300, 600, 900])

# Process the thermal electronic properties
thermal_electronic.process(temperatures=temperatures)

In [7]:
volumes_fit = np.linspace(0.98*60, 1.02*74, 10)
order = 1

# Fit the thermal electronic properties vs. volumes for fixed temperatures
thermal_electronic.fit(volumes_fit=volumes_fit, order=order)

print(thermal_electronic.volumes_fit)
print()
print(thermal_electronic.helmholtz_energies_fit)
print()
print(thermal_electronic.entropies_fit)
print()
print(thermal_electronic.heat_capacities_fit)

# poly_coeffs not tested

[58.8        60.65333333 62.50666667 64.36       66.21333333 68.06666667
 69.92       71.77333333 73.62666667 75.48      ]

[[-5.38607649e-08 -1.31915252e-07 -2.09969739e-07 -2.88024227e-07
  -3.66078714e-07 -4.44133201e-07 -5.22187688e-07 -6.00242175e-07
  -6.78296662e-07 -7.56351150e-07]
 [-1.87473063e-03 -1.91410618e-03 -1.95348174e-03 -1.99285730e-03
  -2.03223285e-03 -2.07160841e-03 -2.11098396e-03 -2.15035952e-03
  -2.18973508e-03 -2.22911063e-03]
 [-7.44612166e-03 -7.60324808e-03 -7.76037450e-03 -7.91750092e-03
  -8.07462735e-03 -8.23175377e-03 -8.38888019e-03 -8.54600661e-03
  -8.70313303e-03 -8.86025946e-03]
 [-1.65318518e-02 -1.68784350e-02 -1.72250181e-02 -1.75716013e-02
  -1.79181845e-02 -1.82647677e-02 -1.86113509e-02 -1.89579341e-02
  -1.93045173e-02 -1.96511004e-02]]

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [1.24917905e-05 1.27560068e-05 1.30202230e-05 1.

In [9]:
# Set volume to only one value and test fit (should raise an error)
thermal_electronic.volumes = np.array([60.])
thermal_electronic.fit(volumes_fit=volumes_fit, order=order)

ValueError: Only one volume found. Need at least two volumes to perform fitting.

# test_plot_total_dos()

In [20]:
# Set the path to the VASP configuration directory and initialize the ThermalElectronic object
config_Al_path = "../vasp_data/Al/config_Al"
thermal_electronic = ThermalElectronic()

In [21]:
# Try to plot without setting the DOS (should raise an error)
thermal_electronic.plot_total_dos()

ValueError: DOS data not found. Please read or set the total electron DOS first using read_total_electron_dos() or set_total_electron_dos().

In [12]:
# Read electron DOS from elec_* folders for all volumes
thermal_electronic.read_total_electron_dos(path=config_Al_path)

/jet/home/nhew/.local/lib/python3.12/site-packages/pymatgen/io/vasp/outputs.py:1285: UserWarning: No POTCAR file with matching TITEL fields was found in

  if potcar := self.get_potcars(path):
/jet/home/nhew/.local/lib/python3.12/site-packages/pymatgen/io/vasp/outputs.py:1296: UserWarning: No POTCAR file with matching TITEL fields was found in

  potcar = self.get_potcars(path)


In [18]:
thermal_electronic.plot_total_dos()

# test_plot_vs_temp()

In [35]:
# Set the path to the VASP configuration directory and initialize the ThermalElectronic object
config_Al_path = "../vasp_data/Al/config_Al"
thermal_electronic = ThermalElectronic()

In [36]:
# Read electron DOS from elec_* folders for all volumes
thermal_electronic.read_total_electron_dos(path=config_Al_path)

In [37]:
# Try to plot without process (should raise an error)
thermal_electronic.plot_vs_temp(property="helmholtz_energy")

ValueError: Thermodynamic properties not yet calculated. Please call process() first.

In [38]:
temperatures = np.array([0, 300, 600, 900])

# Process the thermal electronic properties
thermal_electronic.process(temperatures=temperatures)

In [42]:
# Test the different properties - helmholtz_energy, entropy, heat_capacity
thermal_electronic.plot_vs_temp(property="helmholtz_energy")


In [ ]:
# Test invalid property (should raise an error)
thermal_electronic.plot_vs_volume(property="invalid_property")


# test_plot_vs_volume()

In [65]:
# Set the path to the VASP configuration directory and initialize the ThermalElectronic object
config_Al_path = "../vasp_data/Al/config_Al"
thermal_electronic = ThermalElectronic()

In [66]:
# Read electron DOS from elec_* folders for all volumes
thermal_electronic.read_total_electron_dos(path=config_Al_path)

In [67]:
# Try to plot without process (should raise an error)
thermal_electronic.plot_vs_volume(property="helmholtz_energy")

ValueError: Thermodynamic properties not yet calculated. Please call process() first.

In [68]:
temperatures = np.array([0, 300, 600, 900])

# Process the thermal electronic properties
thermal_electronic.process(temperatures=temperatures)

In [70]:
# Test the different properties - helmholtz_energy, entropy, heat_capacity
thermal_electronic.plot_vs_volume(property="helmholtz_energy")


In [71]:
volumes_fit = np.linspace(0.98*60, 1.02*74, 10)
order = 1

# Fit the thermal electronic properties vs. volumes for fixed temperatures
thermal_electronic.fit(volumes_fit=volumes_fit, order=order)

In [72]:
# Test the different properties - helmholtz_energy, entropy, heat_capacity
thermal_electronic.plot_vs_volume(property="helmholtz_energy")


In [77]:
# Test plot for selected temperatures
thermal_electronic.plot_vs_volume(property="helmholtz_energy", selected_temperatures=[300, 900])

In [78]:
# Test invalid property (should raise an error)
thermal_electronic.plot_vs_volume(property="invalid_property")

ValueError: property must be one of 'helmholtz_energy', 'entropy', or 'heat_capacity'